ALTER TABLE {sc}.DRUG_ERA ADD CONSTRAINT fpk_DRUG_ERA_person_id FOREIGN KEY (person_id) REFERENCES {sc}.PERSON (PERSON_ID);
ALTER TABLE {sc}.DRUG_ERA ADD CONSTRAINT fpk_DRUG_ERA_drug_concept_id FOREIGN KEY (drug_concept_id) REFERENCES {vocab_schema}.CONCEPT (CONCEPT_ID);
ALTER TABLE {sc}.CONDITION_ERA ADD CONSTRAINT fpk_CONDITION_ERA_person_id FOREIGN KEY (person_id) REFERENCES {sc}.PERSON (PERSON_ID);
ALTER TABLE {sc}.CONDITION_ERA ADD CONSTRAINT fpk_CONDITION_ERA_condition_concept_id FOREIGN KEY (condition_concept_id) REFERENCES {vocab_schema}.CONCEPT (CONCEPT_ID);